from vpp_old.motion_detector import csv_name_creator, FPS, resizing,timestamping
#from .realTime_plotting_test2 import onclick_rat1, onclick_rat2, motion_detector_outputs, realTime_plotting
#from .getting_coordinates_manual import coord_extractor
from vpp_old.getting_coordinates_manual_CLASS import Rat_coords
from vpp_old.motion_detector_MVMwriter import motion_detector_MVMwriter
from vpp_old.realTime_plotting_CLASS import Rat_mvm
from vpp_old.mvm2txt import mvm2txt
from vpp_old.normal_fitting import normal_fitting